FROM ubuntu
LABEL Aleksandr Krasnov "alekforwork@gmail.com"
RUN apt-get -y update && \
    apt-get -y upgrade && \
    apt-get install golang-go -y
#for other versions
#add-apt-repository ppa:gophers/archive
#apt-get install golang-1.10-go

